export type pendingMerchantInterface = {
    id: string,
    firstName: string,
    lastName: string,
    role: string,
    phoneNumber: string,
    identification: string,
    services: string[],
    email: string,
    organizationEmail: string,
    emailVerified: boolean,
    is_approved: boolean,
    idempotencyKey: string,
    language: string,
    resetCode: string,
    resetCodeExpire: string,
    is_deleted: boolean,
    is_suspended: boolean,
    lastLogin: string,
    createdAt: string,
    updatedAt: string,
    owner_id: any
}


export type merchantDetailsInterface = {
    id: string,
    password: string,
    firstName: string,
    lastName: string,
    role: string,
    phoneNumber: string,
    identification: string,
    services: string[],
    email: string,
    organizationEmail: string,
    emailVerified: boolean,
    is_approved: boolean,
    idempotencyKey: string,
    language: string,
    resetCode: string,
    resetCodeExpire: string,
    is_deleted: boolean,
    is_suspended: boolean,
    lastLogin: string,
    createdAt: string,
    updatedAt: string,
    owner_id: any
}